export interface CurrencyItem {
  code: string;
  name: string;
  currencySymbol: string;
  symbol: string;
}

export const currencies: CurrencyItem[] = [
  {
    code: 'BRL',
    name: 'Brazilian real',
    currencySymbol: 'R$',
    symbol: 'R$',
  },
  {code: 'USD', name: 'US Dollar', currencySymbol: '$', symbol: '$'},
  {code: 'EUR', name: 'Euro', currencySymbol: '€', symbol: '€'},
  {code: 'JPY', name: 'Japanese yen', currencySymbol: '¥', symbol: '¥'},
  {
    code: 'ADP',
    name: 'Andorran peseta',
    currencySymbol: 'ADP',
    symbol: 'ADP',
  },
  {
    code: 'AED',
    name: 'UAE dirham',
    currencySymbol: 'AED',
    symbol: 'AED',
  },
  {
    code: 'AFA',
    name: 'Afghan afghani (1927–2002)',
    currencySymbol: 'AFA',
    symbol: 'AFA',
  },
  {
    code: 'AFN',
    name: 'Afghan Afghani',
    currencySymbol: 'AFN',
    symbol: '؋',
  },
  {
    code: 'ALK',
    name: 'Albanian lek (1946–1965)',
    currencySymbol: 'ALK',
    symbol: 'ALK',
  },
  {
    code: 'ALL',
    name: 'Albanian lek',
    currencySymbol: 'ALL',
    symbol: 'LEK',
  },
  {
    code: 'AMD',
    name: 'Armenian dram',
    currencySymbol: 'AMD',
    symbol: 'AMD',
  },
  {
    code: 'ANG',
    name: 'Netherlands Antillean guilder',
    currencySymbol: 'ANG',
    symbol: 'ƒ',
  },
  {
    code: 'AOA',
    name: 'Angolan kwanza',
    currencySymbol: 'Kz',
    symbol: 'Kz',
  },
  {
    code: 'AOK',
    name: 'Angolan kwanza (1977–1991)',
    currencySymbol: 'AOK',
    symbol: 'AOK',
  },
  {
    code: 'AON',
    name: 'Angolan new kwanza (1990–2000)',
    currencySymbol: 'AON',
    symbol: 'AON',
  },
  {
    code: 'AOR',
    name: 'Angolan readjusted kwanza (1995–1999)',
    currencySymbol: 'AOR',
    symbol: 'AOR',
  },
  {
    code: 'ARA',
    name: 'Argentine austral',
    currencySymbol: 'ARA',
    symbol: 'ARA',
  },
  {
    code: 'ARL',
    name: 'Argentine peso ley (1970–1983)',
    currencySymbol: 'ARL',
    symbol: 'ARL',
  },
  {
    code: 'ARM',
    name: 'Argentine peso (1881–1970)',
    currencySymbol: 'ARM',
    symbol: 'ARM',
  },
  {
    code: 'ARP',
    name: 'Argentine peso (1983–1985)',
    currencySymbol: 'ARP',
    symbol: 'ARP',
  },
  {
    code: 'ARS',
    name: 'Argentine peso',
    currencySymbol: '$',
    symbol: '$',
  },
  {
    code: 'ATS',
    name: 'Austrian schilling',
    currencySymbol: 'ATS',
    symbol: 'ATS',
  },
  {
    code: 'AUD',
    name: 'Australian dollar',
    currencySymbol: 'A$',
    symbol: '$',
  },
  {
    code: 'AWG',
    name: 'Aruban florin',
    currencySymbol: 'AWG',
    symbol: 'ƒ',
  },
  {
    code: 'AZM',
    name: 'Azerbaijani manat (1993–2006)',
    currencySymbol: 'AZM',
    symbol: 'AZM',
  },
  {
    code: 'AZN',
    name: 'Azerbaijani manat',
    currencySymbol: 'AZN',
    symbol: 'ман',
  },
  {
    code: 'BAD',
    name: 'Bosnia-Herzegovina dinar (1992–1994)',
    currencySymbol: 'BAD',
    symbol: 'BAD',
  },
  {
    code: 'BAM',
    name: 'Bosnia-Herzegovina convertible mark',
    currencySymbol: 'KM',
    symbol: 'KM',
  },
  {
    code: 'BAN',
    name: 'Bosnia-Herzegovina new dinar (1994–1997)',
    currencySymbol: 'BAN',
    symbol: 'BAN',
  },
  {
    code: 'BBD',
    name: 'Barbadian dollar',
    currencySymbol: '$',
    symbol: '$',
  },
  {
    code: 'BDT',
    name: 'Bangladeshi taka',
    currencySymbol: '৳',
    symbol: '৳',
  },
  {
    code: 'BEC',
    name: 'Belgian franc (convertible)',
    currencySymbol: 'BEC',
    symbol: 'BEC',
  },
  {
    code: 'BEF',
    name: 'Belgian franc',
    currencySymbol: 'BEF',
    symbol: 'BEF',
  },
  {
    code: 'BEL',
    name: 'Belgian franc (financial)',
    currencySymbol: 'BEL',
    symbol: 'BEL',
  },
  {
    code: 'BGL',
    name: 'Bulgarian hard lev',
    currencySymbol: 'BGL',
    symbol: 'BGL',
  },
  {
    code: 'BGM',
    name: 'Bulgarian socialist lev',
    currencySymbol: 'BGM',
    symbol: 'BGM',
  },
  {
    code: 'BGN',
    name: 'Bulgarian lev',
    currencySymbol: 'BGN',
    symbol: 'лв',
  },
  {
    code: 'BGO',
    name: 'Bulgarian lev (1879–1952)',
    currencySymbol: 'BGO',
    symbol: 'BGO',
  },
  {
    code: 'BHD',
    name: 'Bahraini dinar',
    currencySymbol: 'BHD',
    symbol: 'BHD',
  },
  {
    code: 'BIF',
    name: 'Burundian franc',
    currencySymbol: 'BIF',
    symbol: 'BIF',
  },
  {
    code: 'BMD',
    name: 'Bermudan dollar',
    currencySymbol: '$',
    symbol: '$',
  },
  {
    code: 'BND',
    name: 'Brunei dollar',
    currencySymbol: '$',
    symbol: '$',
  },
  {
    code: 'BOB',
    name: 'Bolivian boliviano',
    currencySymbol: 'Bs',
    symbol: '$b',
  },
  {
    code: 'BOL',
    name: 'Bolivian boliviano (1863–1963)',
    currencySymbol: 'BOL',
    symbol: 'BOL',
  },
  {
    code: 'BOP',
    name: 'Bolivian peso',
    currencySymbol: 'BOP',
    symbol: 'BOP',
  },
  {
    code: 'BOV',
    name: 'Bolivian mvdol',
    currencySymbol: 'BOV',
    symbol: 'BOV',
  },
  {
    code: 'BRB',
    name: 'Brazilian new cruzeiro (1967–1986)',
    currencySymbol: 'BRB',
    symbol: 'BRB',
  },
  {
    code: 'BRC',
    name: 'Brazilian cruzado (1986–1989)',
    currencySymbol: 'BRC',
    symbol: 'BRC',
  },
  {
    code: 'BRE',
    name: 'Brazilian cruzeiro (1990–1993)',
    currencySymbol: 'BRE',
    symbol: 'BRE',
  },
  {
    code: 'BRN',
    name: 'Brazilian new cruzado (1989–1990)',
    currencySymbol: 'BRN',
    symbol: 'BRN',
  },
  {
    code: 'BRR',
    name: 'Brazilian cruzeiro (1993–1994)',
    currencySymbol: 'BRR',
    symbol: 'BRR',
  },
  {
    code: 'BRZ',
    name: 'Brazilian cruzeiro (1942–1967)',
    currencySymbol: 'BRZ',
    symbol: 'BRZ',
  },
  {
    code: 'BSD',
    name: 'Bahamian dollar',
    currencySymbol: '$',
    symbol: '$',
  },
  {
    code: 'BTN',
    name: 'Bhutanese ngultrum',
    currencySymbol: 'BTN',
    symbol: 'BTN',
  },
  {
    code: 'BUK',
    name: 'Burmese kyat',
    currencySymbol: 'BUK',
    symbol: 'BUK',
  },
  {
    code: 'BWP',
    name: 'Botswanan pula',
    currencySymbol: 'P',
    symbol: 'P',
  },
  {
    code: 'BYB',
    name: 'Belarusian new ruble (1994–1999)',
    currencySymbol: 'BYB',
    symbol: 'BYB',
  },
  {
    code: 'BYR',
    name: 'Belarusian ruble',
    currencySymbol: 'р.',
    symbol: 'p.',
  },
  {
    code: 'BZD',
    name: 'Belize dollar',
    currencySymbol: '$',
    symbol: 'BZ$',
  },
  {
    code: 'CAD',
    name: 'Canadian dollar',
    currencySymbol: 'CA$',
    symbol: '$',
  },
  {
    code: 'CDF',
    name: 'Congolese franc',
    currencySymbol: 'CDF',
    symbol: 'CDF',
  },
  {
    code: 'CHE',
    name: 'WIR euro',
    currencySymbol: 'CHE',
    symbol: 'CHE',
  },
  {
    code: 'CHF',
    name: 'Swiss franc',
    currencySymbol: 'CHF',
    symbol: 'CHF',
  },
  {
    code: 'CHW',
    name: 'WIR franc',
    currencySymbol: 'CHW',
    symbol: 'CHW',
  },
  {
    code: 'CLE',
    name: 'Chilean escudo',
    currencySymbol: 'CLE',
    symbol: 'CLE',
  },
  {
    code: 'CLF',
    name: 'Chilean unit of account (UF)',
    currencySymbol: 'CLF',
    symbol: 'CLF',
  },
  {
    code: 'CLP',
    name: 'Chilean peso',
    currencySymbol: '$',
    symbol: '$',
  },
  {
    code: 'CNX',
    name: 'Chinese People’s Bank dollar',
    currencySymbol: 'CNX',
    symbol: 'CNX',
  },
  {
    code: 'CNY',
    name: 'Chinese yuan',
    currencySymbol: 'CN¥',
    symbol: '¥',
  },
  {
    code: 'COP',
    name: 'Colombian peso',
    currencySymbol: '$',
    symbol: '$',
  },
  {
    code: 'COU',
    name: 'Colombian real value unit',
    currencySymbol: 'COU',
    symbol: 'COU',
  },
  {
    code: 'CRC',
    name: 'Costa Rican colón',
    currencySymbol: '₡',
    symbol: '₡',
  },
  {
    code: 'CSD',
    name: 'Serbian dinar (2002–2006)',
    currencySymbol: 'CSD',
    symbol: 'CSD',
  },
  {
    code: 'CSK',
    name: 'Czechoslovak hard koruna',
    currencySymbol: 'CSK',
    symbol: 'CSK',
  },
  {
    code: 'CUC',
    name: 'Cuban convertible peso',
    currencySymbol: '$',
    symbol: '$',
  },
  {
    code: 'CUP',
    name: 'Cuban peso',
    currencySymbol: '$',
    symbol: '₱',
  },
  {
    code: 'CVE',
    name: 'Cape Verdean escudo',
    currencySymbol: 'CVE',
    symbol: 'CVE',
  },
  {
    code: 'CYP',
    name: 'Cypriot pound',
    currencySymbol: 'CYP',
    symbol: 'CYP',
  },
  {
    code: 'CZK',
    name: 'Czech Republic koruna',
    currencySymbol: 'Kč',
    symbol: 'Kč',
  },
  {
    code: 'DDM',
    name: 'East German mark',
    currencySymbol: 'DDM',
    symbol: 'DDM',
  },
  {
    code: 'DEM',
    name: 'German mark',
    currencySymbol: 'DEM',
    symbol: 'DEM',
  },
  {
    code: 'DJF',
    name: 'Djiboutian franc',
    currencySymbol: 'DJF',
    symbol: 'DJF',
  },
  {
    code: 'DKK',
    name: 'Danish krone',
    currencySymbol: 'kr',
    symbol: 'kr',
  },
  {
    code: 'DOP',
    name: 'Dominican peso',
    currencySymbol: '$',
    symbol: 'RD$',
  },
  {
    code: 'DZD',
    name: 'Algerian dinar',
    currencySymbol: 'DZD',
    symbol: 'DZD',
  },
  {
    code: 'ECS',
    name: 'Ecuadorian sucre',
    currencySymbol: 'ECS',
    symbol: 'ECS',
  },
  {
    code: 'ECV',
    name: 'Ecuadorian unit of constant value',
    currencySymbol: 'ECV',
    symbol: 'ECV',
  },
  {
    code: 'EEK',
    name: 'Estonian kroon',
    currencySymbol: 'EEK',
    symbol: 'kr',
  },
  {
    code: 'EGP',
    name: 'Egyptian pound',
    currencySymbol: 'E£',
    symbol: '£',
  },
  {
    code: 'ERN',
    name: 'Eritrean nakfa',
    currencySymbol: 'ERN',
    symbol: 'ERN',
  },
  {
    code: 'ESA',
    name: 'Spanish peseta (A account)',
    currencySymbol: 'ESA',
    symbol: 'ESA',
  },
  {
    code: 'ESB',
    name: 'Spanish peseta (convertible account)',
    currencySymbol: 'ESB',
    symbol: 'ESB',
  },
  {
    code: 'ESP',
    name: 'Spanish Peseta',
    currencySymbol: '₧',
    symbol: '₧',
  },
  {
    code: 'ETB',
    name: 'Ethiopian Birr',
    currencySymbol: 'ETB',
    symbol: 'ETB',
  },

  {
    code: 'FIM',
    name: 'Finnish Markka',
    currencySymbol: 'FIM',
    symbol: 'FIM',
  },
  {code: 'FJD', name: 'Fijian Dollar', currencySymbol: '$', symbol: '$'},
  {
    code: 'FKP',
    name: 'Falkland Islands Pound',
    currencySymbol: '£',
    symbol: '£',
  },
  {
    code: 'FRF',
    name: 'French Franc',
    currencySymbol: 'FRF',
    symbol: 'FRF',
  },
  {
    code: 'GBP',
    name: 'British Pound Sterling',
    currencySymbol: '£',
    symbol: '£',
  },
  {
    code: 'GEK',
    name: 'Georgian kupon larit',
    currencySymbol: 'GEK',
    symbol: 'GEK',
  },
  {
    code: 'GEL',
    name: 'Georgian lari',
    currencySymbol: 'GEL',
    symbol: 'GEL',
  },
  {
    code: 'GHC',
    name: 'Ghanaian cedi (1979–2007)',
    currencySymbol: 'GHC',
    symbol: 'GHC',
  },
  {
    code: 'GHS',
    name: 'Ghanaian cedi',
    currencySymbol: 'GHS',
    symbol: '¢',
  },
  {
    code: 'GIP',
    name: 'Gibraltar pound',
    currencySymbol: '£',
    symbol: '£',
  },
  {
    code: 'GMD',
    name: 'Gambian dalasi',
    currencySymbol: 'GMD',
    symbol: 'GMD',
  },
  {
    code: 'GNF',
    name: 'Guinean franc',
    currencySymbol: 'FG',
    symbol: 'FG',
  },
  {
    code: 'GNS',
    name: 'Guinean syli',
    currencySymbol: 'GNS',
    symbol: 'GNS',
  },
  {
    code: 'GQE',
    name: 'Equatorial Guinean ekwele',
    currencySymbol: 'GQE',
    symbol: 'GQE',
  },
  {
    code: 'GRD',
    name: 'Greek drachma',
    currencySymbol: 'GRD',
    symbol: 'GRD',
  },
  {
    code: 'GTQ',
    name: 'Guatemalan quetzal',
    currencySymbol: 'Q',
    symbol: 'Q',
  },
  {
    code: 'GWE',
    name: 'Portuguese Guinea escudo',
    currencySymbol: 'GWE',
    symbol: 'GWE',
  },
  {
    code: 'GWP',
    name: 'Guinea-Bissau peso',
    currencySymbol: 'GWP',
    symbol: 'GWP',
  },
  {
    code: 'GYD',
    name: 'Guyanaese dollar',
    currencySymbol: '$',
    symbol: '$',
  },
  {
    code: 'HKD',
    name: 'Hong Kong dollar',
    currencySymbol: 'HK$',
    symbol: '$',
  },
  {
    code: 'HNL',
    name: 'Honduran lempira',
    currencySymbol: 'L',
    symbol: 'L',
  },
  {
    code: 'HRD',
    name: 'Croatian dinar',
    currencySymbol: 'HRD',
    symbol: 'HRD',
  },
  {
    code: 'HRK',
    name: 'Croatian kuna',
    currencySymbol: 'kn',
    symbol: 'kn',
  },
  {
    code: 'HTG',
    name: 'Haitian gourde',
    currencySymbol: 'HTG',
    symbol: 'HTG',
  },
  {
    code: 'HUF',
    name: 'Hungarian forint',
    currencySymbol: 'Ft',
    symbol: 'Ft',
  },
  {
    code: 'IDR',
    name: 'Indonesian Rupiah',
    currencySymbol: 'Rp',
    symbol: 'Rp',
  },
  {
    code: 'IEP',
    name: 'Irish pound',
    currencySymbol: 'IEP',
    symbol: 'IEP',
  },
  {
    code: 'ILP',
    name: 'Israeli Pound',
    currencySymbol: 'ILP',
    symbol: 'ILP',
  },
  {
    code: 'ILR',
    name: 'Israeli Sheqel (1980–1985)',
    currencySymbol: 'ILR',
    symbol: 'ILR',
  },
  {
    code: 'ILS',
    name: 'Israeli New Sheqel',
    currencySymbol: '₪',
    symbol: '₪',
  },
  {
    code: 'INR',
    name: 'Indian Rupee',
    currencySymbol: '₹',
    symbol: '₨',
  },
  {
    code: 'IQD',
    name: 'Iraqi dinar',
    currencySymbol: 'IQD',
    symbol: 'IQD',
  },
  {
    code: 'IRR',
    name: 'Iranian rial',
    currencySymbol: 'IRR',
    symbol: '﷼',
  },
  {
    code: 'ISJ',
    name: 'Icelandic króna (1918–1981)',
    currencySymbol: 'ISJ',
    symbol: 'ISJ',
  },
  {
    code: 'ISK',
    name: 'Icelandic króna',
    currencySymbol: 'kr',
    symbol: 'kr',
  },
  {
    code: 'ITL',
    name: 'Italian lira',
    currencySymbol: 'ITL',
    symbol: 'ITL',
  },
  {
    code: 'JMD',
    name: 'Jamaican dollar',
    currencySymbol: '$',
    symbol: '$',
  },
  {
    code: 'JOD',
    name: 'Jordanian dinar',
    currencySymbol: 'JOD',
    symbol: 'JOD',
  },

  {
    code: 'KES',
    name: 'Kenyan shilling',
    currencySymbol: 'KES',
    symbol: 'KES',
  },
  {
    code: 'KGS',
    name: 'Kyrgystani som',
    currencySymbol: 'KGS',
    symbol: 'лв',
  },
  {
    code: 'KHR',
    name: 'Cambodian riel',
    currencySymbol: '៛',
    symbol: '៛',
  },
  {
    code: 'KMF',
    name: 'Comorian franc',
    currencySymbol: 'CF',
    symbol: 'CF',
  },
  {
    code: 'KPW',
    name: 'North Korean won',
    currencySymbol: '₩',
    symbol: '₩',
  },
  {
    code: 'KRH',
    name: 'South Korean hwan (1953–1962)',
    currencySymbol: 'KRH',
    symbol: 'KRH',
  },
  {
    code: 'KRO',
    name: 'South Korean won (1945–1953)',
    currencySymbol: 'KRO',
    symbol: 'KRO',
  },
  {
    code: 'KRW',
    name: 'South Korean won',
    currencySymbol: '₩',
    symbol: '₩',
  },
  {
    code: 'KWD',
    name: 'Kuwaiti dinar',
    currencySymbol: 'KWD',
    symbol: 'KWD',
  },
  {
    code: 'KYD',
    name: 'Cayman Islands dollar',
    currencySymbol: '$',
    symbol: '$',
  },
  {
    code: 'KZT',
    name: 'Kazakhstani tenge',
    currencySymbol: '₸',
    symbol: 'лв',
  },
  {code: 'LAK', name: 'Laotian kip', currencySymbol: '₭', symbol: '₭'},
  {
    code: 'LBP',
    name: 'Lebanese Pound',
    currencySymbol: 'L£',
    symbol: '£',
  },
  {
    code: 'LKR',
    name: 'Sri Lankan rupee',
    currencySymbol: 'Rs',
    symbol: '₨',
  },
  {
    code: 'LRD',
    name: 'Liberian dollar',
    currencySymbol: '$',
    symbol: '$',
  },
  {
    code: 'LSL',
    name: 'Lesotho loti',
    currencySymbol: 'LSL',
    symbol: 'LSL',
  },
  {
    code: 'LTL',
    name: 'Lithuanian litas',
    currencySymbol: 'Lt',
    symbol: 'Lt',
  },
  {
    code: 'LTT',
    name: 'Lithuanian talonas',
    currencySymbol: 'LTT',
    symbol: 'LTT',
  },
  {
    code: 'LUC',
    name: 'Luxembourgian convertible franc',
    currencySymbol: 'LUC',
    symbol: 'LUC',
  },
  {
    code: 'LUF',
    name: 'Luxembourgian franc',
    currencySymbol: 'LUF',
    symbol: 'LUF',
  },
  {
    code: 'LUL',
    name: 'Luxembourg financial franc',
    currencySymbol: 'LUL',
    symbol: 'LUL',
  },
  {
    code: 'LVL',
    name: 'Latvian lats',
    currencySymbol: 'Ls',
    symbol: 'Ls',
  },
  {
    code: 'LVR',
    name: 'Latvian ruble',
    currencySymbol: 'LVR',
    symbol: 'LVR',
  },
  {
    code: 'LYD',
    name: 'Libyan dinar',
    currencySymbol: 'LYD',
    symbol: 'LYD',
  },
  {
    code: 'MAD',
    name: 'Moroccan dirham',
    currencySymbol: 'MAD',
    symbol: 'MAD',
  },
  {
    code: 'MAF',
    name: 'Moroccan franc',
    currencySymbol: 'MAF',
    symbol: 'MAF',
  },
  {
    code: 'MCF',
    name: 'Monegasque franc',
    currencySymbol: 'MCF',
    symbol: 'MCF',
  },
  {
    code: 'MDC',
    name: 'Moldovan cupon',
    currencySymbol: 'MDC',
    symbol: 'MDC',
  },
  {
    code: 'MDL',
    name: 'Moldovan leu',
    currencySymbol: 'MDL',
    symbol: 'MDL',
  },
  {
    code: 'MGA',
    name: 'Malagasy Ariary',
    currencySymbol: 'Ar',
    symbol: 'Ar',
  },
  {
    code: 'MGF',
    name: 'Malagasy franc',
    currencySymbol: 'MGF',
    symbol: 'MGF',
  },
  {
    code: 'MKD',
    name: 'Macedonian denar',
    currencySymbol: 'MKD',
    symbol: 'MKD',
  },
  {
    code: 'MKN',
    name: 'Macedonian denar (1992–1993)',
    currencySymbol: 'MKN',
    symbol: 'MKN',
  },
  {
    code: 'MLF',
    name: 'Malian franc',
    currencySymbol: 'MLF',
    symbol: 'MLF',
  },
  {code: 'MMK', name: 'Myanmar kyat', currencySymbol: 'K', symbol: 'K'},
  {
    code: 'MNT',
    name: 'Mongolian tugrik',
    currencySymbol: '₮',
    symbol: '₮',
  },
  {
    code: 'MOP',
    name: 'Macanese pataca',
    currencySymbol: 'MOP',
    symbol: 'MOP',
  },
  {
    code: 'MRO',
    name: 'Mauritanian ouguiya',
    currencySymbol: 'MRO',
    symbol: 'MRO',
  },
  {
    code: 'MTL',
    name: 'Maltese lira',
    currencySymbol: 'MTL',
    symbol: 'MTL',
  },
  {
    code: 'MTP',
    name: 'Maltese pound',
    currencySymbol: 'MTP',
    symbol: 'MTP',
  },
  {
    code: 'MUR',
    name: 'Mauritian rupee',
    currencySymbol: 'Rs',
    symbol: '₨',
  },
  {
    code: 'MVP',
    name: 'Maldivian rupee (1947–1981)',
    currencySymbol: 'MVP',
    symbol: 'MVP',
  },
  {
    code: 'MVR',
    name: 'Maldivian rufiyaa',
    currencySymbol: 'MVR',
    symbol: 'MVR',
  },
  {
    code: 'MWK',
    name: 'Malawian Kwacha',
    currencySymbol: 'MWK',
    symbol: 'MWK',
  },
  {
    code: 'MXN',
    name: 'Mexican peso',
    currencySymbol: 'MX$',
    symbol: '$',
  },
  {
    code: 'MXP',
    name: 'Mexican silver peso (1861–1992)',
    currencySymbol: 'MXP',
    symbol: 'MXP',
  },
  {
    code: 'MXV',
    name: 'Mexican investment unit',
    currencySymbol: 'MXV',
    symbol: 'MXV',
  },
  {
    code: 'MYR',
    name: 'Malaysian ringgit',
    currencySymbol: 'RM',
    symbol: 'RM',
  },
  {
    code: 'MZE',
    name: 'Mozambican escudo',
    currencySymbol: 'MZE',
    symbol: 'MZE',
  },
  {
    code: 'MZM',
    name: 'Mozambican metical (1980–2006)',
    currencySymbol: 'MZM',
    symbol: 'MZM',
  },
  {
    code: 'MZN',
    name: 'Mozambican metical',
    currencySymbol: 'MZN',
    symbol: 'MT',
  },
  {
    code: 'NAD',
    name: 'Namibian dollar',
    currencySymbol: '$',
    symbol: '$',
  },
  {
    code: 'NGN',
    name: 'Nigerian naira',
    currencySymbol: '₦',
    symbol: '₦',
  },
  {
    code: 'NIC',
    name: 'Nicaraguan córdoba (1988–1991)',
    currencySymbol: 'NIC',
    symbol: 'NIC',
  },
  {
    code: 'NIO',
    name: 'Nicaraguan córdoba',
    currencySymbol: 'C$',
    symbol: 'C$',
  },
  {
    code: 'NLG',
    name: 'Dutch guilder',
    currencySymbol: 'NLG',
    symbol: 'NLG',
  },
  {
    code: 'NOK',
    name: 'Norwegian krone',
    currencySymbol: 'kr',
    symbol: 'kr',
  },
  {
    code: 'NPR',
    name: 'Nepalese rupee',
    currencySymbol: 'Rs',
    symbol: '₨',
  },
  {
    code: 'NZD',
    name: 'New Zealand dollar',
    currencySymbol: 'NZ$',
    symbol: '$',
  },
  {
    code: 'OMR',
    name: 'Omani rial',
    currencySymbol: 'OMR',
    symbol: '﷼',
  },
  {
    code: 'PAB',
    name: 'Panamanian balboa',
    currencySymbol: 'PAB',
    symbol: 'B/.',
  },
  {
    code: 'PEI',
    name: 'Peruvian inti',
    currencySymbol: 'PEI',
    symbol: 'PEI',
  },
  {
    code: 'PEN',
    name: 'Peruvian nuevo sol',
    currencySymbol: 'PEN',
    symbol: 'S/.',
  },
  {
    code: 'PES',
    name: 'Peruvian sol (1863–1965)',
    currencySymbol: 'PES',
    symbol: 'PES',
  },
  {
    code: 'PGK',
    name: 'Papua New Guinean kina',
    currencySymbol: 'PGK',
    symbol: 'PGK',
  },
  {
    code: 'PHP',
    name: 'Philippine peso',
    currencySymbol: '₱',
    symbol: 'Php',
  },
  {
    code: 'PKR',
    name: 'Pakistani rupee',
    currencySymbol: 'Rs',
    symbol: '₨',
  },
  {
    code: 'PLN',
    name: 'Polish zloty',
    currencySymbol: 'zł',
    symbol: 'zł',
  },
  {
    code: 'PLZ',
    name: 'Polish zloty (PLZ)',
    currencySymbol: 'PLZ',
    symbol: 'PLZ',
  },
  {
    code: 'PTE',
    name: 'Portuguese escudo',
    currencySymbol: 'PTE',
    symbol: 'PTE',
  },
  {
    code: 'PYG',
    name: 'Paraguayan guarani',
    currencySymbol: '₲',
    symbol: 'Gs',
  },
  {
    code: 'QAR',
    name: 'Qatari rial',
    currencySymbol: 'QAR',
    symbol: '﷼',
  },
  {
    code: 'RHD',
    name: 'Rhodesian dollar',
    currencySymbol: 'RHD',
    symbol: 'RHD',
  },
  {
    code: 'ROL',
    name: 'Romanian leu (1952–2006)',
    currencySymbol: 'ROL',
    symbol: 'ROL',
  },
  {
    code: 'RON',
    name: 'Romanian leu',
    currencySymbol: 'RON',
    symbol: 'lei',
  },
  {
    code: 'RSD',
    name: 'Serbian dinar',
    currencySymbol: 'RSD',
    symbol: 'Дин.',
  },
  {
    code: 'RUB',
    name: 'Russian ruble',
    currencySymbol: '₽',
    symbol: 'руб',
  },
  {
    code: 'RUR',
    name: 'Russian ruble (1991–1998)',
    currencySymbol: 'р.',
    symbol: 'р.',
  },
  {
    code: 'RWF',
    name: 'Rwandan franc',
    currencySymbol: 'RF',
    symbol: 'RF',
  },
  {
    code: 'SAR',
    name: 'Saudi riyal',
    currencySymbol: 'SAR',
    symbol: '﷼',
  },
  {
    code: 'SBD',
    name: 'Solomon Islands dollar',
    currencySymbol: '$',
    symbol: '$',
  },
  {
    code: 'SCR',
    name: 'Seychellois rupee',
    currencySymbol: 'SCR',
    symbol: '₨',
  },
  {
    code: 'SDD',
    name: 'Sudanese dinar (1992–2007)',
    currencySymbol: 'SDD',
    symbol: 'SDD',
  },
  {
    code: 'SDG',
    name: 'Sudanese pound',
    currencySymbol: 'SDG',
    symbol: 'SDG',
  },
  {
    code: 'SDP',
    name: 'Sudanese pound (1957–1998)',
    currencySymbol: 'SDP',
    symbol: 'SDP',
  },
  {
    code: 'SEK',
    name: 'Swedish krona',
    currencySymbol: 'kr',
    symbol: 'kr',
  },
  {
    code: 'SGD',
    name: 'Singapore dollar',
    currencySymbol: '$',
    symbol: '$',
  },
  {
    code: 'SHP',
    name: 'St. Helena pound',
    currencySymbol: '£',
    symbol: '£',
  },
  {
    code: 'SIT',
    name: 'Slovenian tolar',
    currencySymbol: 'SIT',
    symbol: 'SIT',
  },
  {
    code: 'SKK',
    name: 'Slovak koruna',
    currencySymbol: 'SKK',
    symbol: 'SKK',
  },
  {
    code: 'SLL',
    name: 'Sierra Leonean leone',
    currencySymbol: 'SLL',
    symbol: 'SLL',
  },
  {
    code: 'SOS',
    name: 'Somali shilling',
    currencySymbol: 'SOS',
    symbol: 'S',
  },
  {
    code: 'SRD',
    name: 'Surinamese dollar',
    currencySymbol: '$',
    symbol: '$',
  },
  {
    code: 'SRG',
    name: 'Surinamese guilder',
    currencySymbol: 'SRG',
    symbol: 'SRG',
  },
  {
    code: 'SSP',
    name: 'South Sudanese pound',
    currencySymbol: '£',
    symbol: '£',
  },
  {
    code: 'STD',
    name: 'São Tomé \u0026 Príncipe dobra',
    currencySymbol: 'Db',
    symbol: 'Db',
  },
  {
    code: 'SUR',
    name: 'Soviet rouble',
    currencySymbol: 'SUR',
    symbol: 'SUR',
  },
  {
    code: 'SVC',
    name: 'Salvadoran colón',
    currencySymbol: 'SVC',
    symbol: 'SVC',
  },
  {code: 'SYP', name: 'Syrian pound', currencySymbol: '£', symbol: '£'},
  {
    code: 'SZL',
    name: 'Swazi lilangeni',
    currencySymbol: 'SZL',
    symbol: 'SZL',
  },
  {code: 'THB', name: 'Thai baht', currencySymbol: '฿', symbol: '฿'},
  {
    code: 'TJR',
    name: 'Tajikistani ruble',
    currencySymbol: 'TJR',
    symbol: 'TJR',
  },
  {
    code: 'TJS',
    name: 'Tajikistani somoni',
    currencySymbol: 'TJS',
    symbol: 'TJS',
  },
  {
    code: 'TMM',
    name: 'Turkmenistani manat (1993–2009)',
    currencySymbol: 'TMM',
    symbol: 'TMM',
  },
  {
    code: 'TMT',
    name: 'Turkmenistani manat',
    currencySymbol: 'TMT',
    symbol: 'TMT',
  },
  {
    code: 'TND',
    name: 'Tunisian dinar',
    currencySymbol: 'TND',
    symbol: 'TND',
  },
  {
    code: 'TOP',
    name: 'Tongan paʻanga',
    currencySymbol: 'T$',
    symbol: 'T$',
  },
  {
    code: 'TPE',
    name: 'Timorese escudo',
    currencySymbol: 'TPE',
    symbol: 'TPE',
  },
  {
    code: 'TRL',
    name: 'Turkish lira (1922–2005)',
    currencySymbol: 'TRL',
    symbol: 'TRL',
  },
  {
    code: 'TRY',
    name: 'Turkish lira',
    currencySymbol: '₺',
    symbol: 'TL',
  },
  {
    code: 'TTD',
    name: 'Trinidad \u0026 Tobago dollar',
    currencySymbol: '$',
    symbol: '$',
  },
  {
    code: 'TWD',
    name: 'New Taiwan dollar',
    currencySymbol: 'NT$',
    symbol: 'NT$',
  },
  {
    code: 'TZS',
    name: 'Tanzanian shilling',
    currencySymbol: 'TZS',
    symbol: 'TZS',
  },
  {
    code: 'UAH',
    name: 'Ukrainian hryvnia',
    currencySymbol: '₴',
    symbol: '₴',
  },
  {
    code: 'UAK',
    name: 'Ukrainian karbovanets',
    currencySymbol: 'UAK',
    symbol: 'UAK',
  },
  {
    code: 'UGS',
    name: 'Ugandan shilling (1966–1987)',
    currencySymbol: 'UGS',
    symbol: 'UGS',
  },
  {
    code: 'UGX',
    name: 'Ugandan shilling',
    currencySymbol: 'UGX',
    symbol: 'UGX',
  },

  {
    code: 'USN',
    name: 'US dollar (next day)',
    currencySymbol: 'USN',
    symbol: 'USN',
  },
  {
    code: 'USS',
    name: 'US dollar (same day)',
    currencySymbol: 'USS',
    symbol: 'USS',
  },
  {
    code: 'UYI',
    name: 'Uruguayan peso (indexed units)',
    currencySymbol: 'UYI',
    symbol: 'UYI',
  },
  {
    code: 'UYP',
    name: 'Uruguayan peso (1975–1993)',
    currencySymbol: 'UYP',
    symbol: 'UYP',
  },
  {
    code: 'UYU',
    name: 'Uruguayan peso',
    currencySymbol: '$',
    symbol: '$U',
  },
  {
    code: 'UZS',
    name: 'Uzbekistan som',
    currencySymbol: 'UZS',
    symbol: 'лв',
  },
  {
    code: 'VEB',
    name: 'Venezuelan bolívar (1871–2008)',
    currencySymbol: 'VEB',
    symbol: 'VEB',
  },
  {
    code: 'VEF',
    name: 'Venezuelan bolívar',
    currencySymbol: 'Bs',
    symbol: 'Bs',
  },
  {
    code: 'VND',
    name: 'Vietnamese dong',
    currencySymbol: '₫',
    symbol: '₫',
  },
  {
    code: 'VNN',
    name: 'Vietnamese dong (1978–1985)',
    currencySymbol: 'VNN',
    symbol: 'VNN',
  },
  {
    code: 'VUV',
    name: 'Vanuatu vatu',
    currencySymbol: 'VUV',
    symbol: 'VUV',
  },
  {
    code: 'WST',
    name: 'Samoan tala',
    currencySymbol: 'WST',
    symbol: 'WST',
  },
  {
    code: 'XAF',
    name: 'CFA franc BEAC',
    currencySymbol: 'FCFA',
    symbol: 'FCFA',
  },
  {
    code: 'XAG',
    name: 'troy ounce of silver',
    currencySymbol: 'XAG',
    symbol: 'XAG',
  },
  {
    code: 'XAU',
    name: 'troy ounce of gold',
    currencySymbol: 'XAU',
    symbol: 'XAU',
  },
  {
    code: 'XBA',
    name: 'European composite unit',
    currencySymbol: 'XBA',
    symbol: 'XBA',
  },
  {
    code: 'XBB',
    name: 'European monetary unit',
    currencySymbol: 'XBB',
    symbol: 'XBB',
  },
  {
    code: 'XBC',
    name: 'European unit of account (XBC)',
    currencySymbol: 'XBC',
    symbol: 'XBC',
  },
  {
    code: 'XBD',
    name: 'European unit of account (XBD)',
    currencySymbol: 'XBD',
    symbol: 'XBD',
  },
  {
    code: 'XCD',
    name: 'East Caribbean dollar',
    currencySymbol: 'EC$',
    symbol: '$',
  },
  {
    code: 'XDR',
    name: 'special drawing rights',
    currencySymbol: 'XDR',
    symbol: 'XDR',
  },
  {
    code: 'XEU',
    name: 'European code unit',
    currencySymbol: 'XEU',
    symbol: 'XEU',
  },
  {
    code: 'XFO',
    name: 'French gold franc',
    currencySymbol: 'XFO',
    symbol: 'XFO',
  },
  {
    code: 'XFU',
    name: 'French UIC-franc',
    currencySymbol: 'XFU',
    symbol: 'XFU',
  },
  {
    code: 'XOF',
    name: 'CFA franc BCEAO',
    currencySymbol: 'CFA',
    symbol: 'CFA',
  },
  {
    code: 'XPD',
    name: 'troy ounce of palladium',
    currencySymbol: 'XPD',
    symbol: 'XPD',
  },
  {
    code: 'XPF',
    name: 'CFP franc',
    currencySymbol: 'CFPF',
    symbol: 'CFPF',
  },
  {
    code: 'XPT',
    name: 'troy ounce of platinum',
    currencySymbol: 'XPT',
    symbol: 'XPT',
  },
  {
    code: 'XRE',
    name: 'RINET Funds Unit',
    currencySymbol: 'XRE',
    symbol: 'XRE',
  },
  {
    code: 'XSU',
    name: 'Sucre',
    currencySymbol: 'XSU',
    symbol: 'XSU',
  },
  {
    code: 'XTS',
    name: 'Testing Currency Unit',
    currencySymbol: 'XTS',
    symbol: 'XTS',
  },
  {
    code: 'XUA',
    name: 'ADB Unit Of Account',
    currencySymbol: 'XUA',
    symbol: 'XUA',
  },
  {
    code: 'XXX',
    name: '(unknown unit of code)',
    currencySymbol: 'XXX',
    symbol: 'XXX',
  },
  {
    code: 'YDD',
    name: 'Yemeni Dinar',
    currencySymbol: 'YDD',
    symbol: 'YDD',
  },
  {
    code: 'YER',
    name: 'Yemeni Rial',
    currencySymbol: 'YER',
    symbol: '﷼',
  },
  {
    code: 'YUD',
    name: 'Yugoslavian Hard Dinar (1966–1990)',
    currencySymbol: 'YUD',
    symbol: 'YUD',
  },
  {
    code: 'YUM',
    name: 'Yugoslavian New Dinar (1994–2002)',
    currencySymbol: 'YUM',
    symbol: 'YUM',
  },
  {
    code: 'YUN',
    name: 'Yugoslavian Convertible Dinar (1990–1992)',
    currencySymbol: 'YUN',
    symbol: 'YUN',
  },
  {
    code: 'YUR',
    name: 'Yugoslavian Reformed Dinar (1992–1993)',
    currencySymbol: 'YUR',
    symbol: 'YUR',
  },
  {
    code: 'ZAL',
    name: 'South African Rand (financial)',
    currencySymbol: 'ZAL',
    symbol: 'ZAL',
  },
  {
    code: 'ZAR',
    name: 'South African Rand',
    currencySymbol: 'R',
    symbol: 'R',
  },
  {
    code: 'ZMK',
    name: 'Zambian Kwacha (1968–2012)',
    currencySymbol: 'ZMK',
    symbol: 'ZMK',
  },
  {
    code: 'ZMW',
    name: 'Zambian Kwacha',
    currencySymbol: 'ZK',
    symbol: 'ZK',
  },
  {
    code: 'ZRN',
    name: 'Zairean New Zaire (1993–1998)',
    currencySymbol: 'ZRN',
    symbol: 'ZRN',
  },
  {
    code: 'ZRZ',
    name: 'Zairean Zaire (1971–1993)',
    currencySymbol: 'ZRZ',
    symbol: 'ZRZ',
  },
  {
    code: 'ZWD',
    name: 'Zimbabwean Dollar (1980–2008)',
    currencySymbol: 'ZWD',
    symbol: 'Z$',
  },
  {
    code: 'ZWL',
    name: 'Zimbabwean Dollar (2009)',
    currencySymbol: 'ZWL',
    symbol: 'ZWL',
  },
  {
    code: 'ZWR',
    name: 'Zimbabwean Dollar (2008)',
    currencySymbol: 'ZWR',
    symbol: 'ZWR',
  },
];

export default currencies;
